/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.airline_reservation_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JMS
 */
public class Ticket_Report extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ticket_Report
     */
    public Ticket_Report() {
        initComponents();
        loadData();
    }
    Connection con;
    PreparedStatement pre;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jTable1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TicketId", "FlightId", "CustomerId", "Class", "Prise", "Seats", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("TicketId");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("FlightId");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("CustomerId");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Class");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Prise");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Seats");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Date");
        }

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Cancle");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public void loadData()
    {
        try {
            // TODO add your handling code here:
            
            
            Class.forName("com.mysql.jdbc.Driver");
            
            String url="jdbc:mysql://localhost/airlinedb";
            String username="root";
            String password="Pass@123";
            
            con=DriverManager.getConnection(url,username,password);
            
            String query="select * from ticket";
            pre=con.prepareStatement(query);
          
            ResultSet rs=pre.executeQuery();
            
            ResultSetMetaData rsm=rs.getMetaData();
            int c;
            c = rsm.getColumnCount();
            
            DefaultTableModel dtf =  (DefaultTableModel)jTable1.getModel();
            dtf.setRowCount(0);
            
            while(rs.next())
            {
                Vector V2=new Vector();
                for(int i=0;i<=c;i++){
                    V2.add(rs.getString("idticket"));
                    V2.add(rs.getString("flightid"));
                    V2.add(rs.getString("custid"));
                    V2.add(rs.getString("class"));
                    V2.add(rs.getString("price"));
                    V2.add(rs.getString("seats"));
                    V2.add(rs.getString("date"));
                 ;
                }
                dtf.addRow(V2);
            }
                
                
            
            
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
